#image: dbox/gwms-test:latest
before_script:
    - printenv | sort > output
    - pwd >> output
    - find . -ls >> output
    - cat output

# Full project: https://gitlab.com/pages/plain-html 
pages:   
  stage: deploy   
  script:   
  - mkdir .public   
  - cp -r * .public   
  - mv .public public   
  artifacts:     
    paths:     
    - public   
    only:   
    - master


