sudo: required
services:
- docker
language:
- python
before_install:
- git clean -f -d
- docker build -t dbox/gwms-test:latest .
- docker build --build-arg rel=7 -t dbox/gwms-test:sl7 .
- docker build --build-arg rel=6 -t dbox/gwms-test:sl6 .
- docker run --rm  dbox/gwms-test new_gwms_branches 10
- docker ps -a
- docker run dbox/gwms-test help
script:
- docker run dbox/gwms-test help > index.html
- find . -ls > documents/index.html 2>&1
- cp documents/index.html documents/list.$(date +%s)
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push  dbox/gwms-test:latest
- docker push  dbox/gwms-test:sl7
- docker push  dbox/gwms-test:sl6
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  file: documents/index.html
  on:
    branch: master
env:
  matrix:
  - secure: glP7pm4jBW+4zhIuHywxUwshls4BZE6TO4a4xgEmBm4pmMLAd4NFMuLi0eZfiNgkQRpupVugX5MVsbkF62yEBDue4ONQOla7b3+wQG9qGIp1Z2xKGCf/fko8Q5nbDQ3aarUx2Kx/EKcIDPFlACdpClDYfWJbZSPhMYfMGbdkSP/96yRC3yauB8PXqiXeYSDXNbuwldV8W09fhYoKvoG7Lndo5AXycRxdY726FcMqSxAdGUKPI9EZxnxUrep8pVaJXwGJfu+ZffH55fJTtK/3GBj3emJwi9He5s+LFYtmXkT4UFLFAyT5xNJHMvY4fdW5cmv+cTZKDeGC5TSH5u5LVTD90+DZl92YwKvWdsNG3BL7Z2dtZscisgp/TjSQbwWKbq7m+7ODtDcE3ZCfwr2xzDPtF0zC/Wt6WIa23X6Wj+qaVbADKv57TjmjhbNAvnuEzh+EDqGAb3NyCsuGPA/FIprTEYPbR4GlyDcVs3luGdFN/tbezYCe7kwEWE94Wi8vwGMtzmxzgxKJm2p5q29togjAnxmKhcsQevTtg7HAo+dAxUljFQqHv9NLK8usZwnVRzPhmVL2sluWSG3fHOi1XKrjN1pivq5wR/DzkLtlNJYhAg9DT+wTh8Y+96UUZayWSj26CIJokHIIFuvseBSMBarAlnh4LNmjNgtAq+QBYZ0=
  - secure: l/xz485P54NcveBI9uOT3lFOAkvCKJOXsseAvB8pQZzjUlnsv/uMOB1ZzB5KpNxCKmVDGkcTtTinZXvxb1e6o4jrOtL9NLYiizuCEBXbkaPfpVh0Gwmv5uUV+k1N7L1UnmAGfc7WZE8jqd/meOeWcAgsC6rU1f1aETahq8HLnmn6rs77zchwKgRIp15GquO3rkdR2BUk5DR3qNCbk9o8zhEyceTlAjkEbyNangg1z8yyr3sUt/QQSCfdDdTDYtSkwMMTsen5N5F2FUj4GLOpxTNEEqR0LGd8r1/z2CH3yJ+u7IUZ8SBwO8qd3nIVyxBMAAlAij2zDvzPiIVtTEXtM5ViZqssvxFyWUhGySLqzBSVKqZiCl/kFvOQeyG6VESe7M4oJejv34w3tiQXwatjy/d700NcS2szHjGhqd4lYyNToS2lnAurP6Z8YuwMHQDmbZ9leBLhwAb+EykcbXJkTkWFT9k0h1wznCsqiq081kuuQtm4gCsET4A3GKZqDgu1oETBeS9Qb8al5NQsLMTM1f710cLeq47Xz1DnX4CcBSSD2POSdiJOtdcGMI8cBpMIJVHaOXSv0srkBbTHiFBNnxFGX/h3/SOD27WoHmSlIJi5XO1QFXGk0vwc3KddaxFcxNqON1VlF1JzubTkcBh4t8/hYPzgRS3iGsLOgVgwN6U=
  - secure: nM96ObW7IqwVPLMe7HUbKNADuuiadJD93rLCKJfak1Ff5xbOLDk2T8cqHKgMYrHTRmFzhGn5JuX4vwayULnWjZ+tYTUGrHaGEl4kaM8tNgYLGcsNBbTJUHk5NRygTebuHz4CQeMdFo5f8G23HyBADPbfULnv2lw0u6J2WTTTMmQsV56LRjWPJzn1/+A5W8SgkvGlAj8rOnE5HWb6j+LFEZB/AtFTgrAeIg116COKuPnigK81shoXwAEs7oCpWzraZb474bHyhJ12+a6Bs8WpgTRnXsKuzC3Nl1ayOpO3yftwecYYzx6ykrq0gV7IFta+R8xG7OQk+naBbvTt5JO8p7/6LmaTy2ShNAgRYTK5MJpKSLzgtbKpQWOxm/fklsQ3C2bs8v1hn9xBd2T6hUahde2hRoPvAN0SADHqxJ2n2omZSCODtmbjHQmNjAATJP3tyces3Hk2XECu79W1CzHSgQTIg7l2FXU+iiL1ysYnLC5pNzQUVNuFUDhCawEXAbUQ0DhgZzjO3U8860tWba+9J7mrUPm+Ue2P72Gkq1JqPTjX/ZlDq3un8x36zdRO1bMRTbnby4Smsk+lpLQNBNaBQy4rz8gelJWS+MVso4zLwSP9a3I9AU8MtvKsrqvzLQOigmoBxS1oyyC1oiFI5QmZhnOl7JX0bsadumhho9YOYTw=
