#!/bin/sh
if [ "$1" = "" ]; then
    this=$(basename "$0")
    echo "usage:  $this   n "
    echo "where n is number of days:"
    echo "returns a list of branches in the glideinwms repository that have changed in the last n days"
    exit 1
fi
cd "$TEST_DIR"
rm -rf glideinwms
git clone https://github.com/glideinWMS/glideinwms.git > /dev/null 2>&1
cd glideinwms
git log --all --oneline --since="$1 days ago" --pretty=format:%d | tr ',' '\n' | tr '(' ' ' | tr ')' ' ' | grep origin | sed -e 's/.*origin\///' -e 's/HEAD/master/' | sort |uniq | tr '\n' ' '; echo
