#!/bin/bash
. /usr/local/lib/test_lib.sh

if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi

if ! test -f "${VIRTUAL_ENV}/bin/activate"; then
    prep_venv
    source "${VIRTUAL_ENV}/bin/activate"
fi

try cd "$TEST_DIR"/"$PROJECT"

mybranch=$(thisbranch)

if [ "$mybranch" != "$branch" ]; then
    checkout_branch "$branch"
    prep_branch
fi

try cd "$TEST_DIR"
no_slash="${TEST_DIR}"/output/$(echo "$branch" | sed -e 's/\//_/g')
mkdir -p "$no_slash"
/bin/bash ./glideinwms/build/jenkins/run_pylint.sh 2>&1 | tee "${no_slash}/pylint.log"
mv ./*.log "$no_slash"
