#!/bin/sh
. /usr/local/lib/test_lib.sh

if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi

if ! test -f "$VIRTUAL_ENV"/bin/activate; then
    prep_venv
    . "$VIRTUAL_ENV"/bin/activate
fi

try cd "$TEST_DIR"/"$PROJECT"

mybranch=$(thisbranch)

if [ "$mybranch" != "$branch" ]; then
    checkout_branch "$branch"
    prep_branch 
fi


try cd "$TEST_DIR"

branch_dir="$TEST_DIR"/output/$(echo "$branch"| sed -e 's/\//_/g')
mkdir -p  "$branch_dir/futurize"
/bin/bash ./glideinwms/build/jenkins/run_futurize.sh -i  "$branch_dir"/futurize 2>&1 | tee "$branch_dir"/futurize.log
