#!/bin/sh
cd /gwms_test/glideinwms
if [ "$1" == "" ]; then
    branch="master"
else
    branch=$1
fi
git checkout $branch
cd build/jenkins
for F in $(cat /gwms_test/jenkins_scripts); do git checkout master $F; done
cd /gwms_test
source $VIRTUAL_ENV/bin/activate
no_slash=output/$(echo $branch| sed -e 's/\//_/g')
mkdir -p $no_slash
./glideinwms/build/jenkins/run_pylint.sh 2>&1 | tee $no_slash/pylint.log
mv *.log $no_slash
