#!/bin/sh
. /usr/local/lib/test_lib.sh

if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi

if ! test -f "$VIRTUAL_ENV"/bin/activate; then
    prep_venv
    . "$VIRTUAL_ENV"/bin/activate
fi

try cd "$TEST_DIR/$PROJECT"

mybranch=$(thisbranch)

if [ "$mybranch" != "$branch" ]; then
    checkout_branch "$branch"
    prep_branch 
fi


try cd "$TEST_DIR"
branch_dir=${TEST_DIR}/output/$(echo "$branch"| sed -e 's/\//_/g')
mkdir -p  "$branch_dir/xml_reports"
/bin/bash  ./glideinwms/build/jenkins/run_unittests.sh -ac 2>&1 | tee "$branch_dir"/unit_test.log
mv ./glideinwms/unittests/unittests-reports/* "$branch_dir/xml_reports"
mv ./htmlcov* "$branch_dir"
mv ./coverage.report.* "$branch_dir"
mv ./*.out "$branch_dir"
mv ./*.log "$branch_dir"
