#!/bin/bash
# file: setup_test_env
# purpose: set up a glideinwms branch "$1" for lint and unit tests
# author: Dennis Box, dbox@fnal.gov

. /usr/local/lib/test_lib.sh

ci_branch='master'
if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi

checkout_branch $branch
prep_branch $ci_branch

if ! test -f $TEST_DIR/venv-2.${rel}/bin/activate ; then
    prep_venv
    source ~/.bashrc
fi
cd $TEST_DIR
rm -rf output || true
mkdir -p output
