#!/bin/bash -x
cd "$TEST_DIR/$PROJECT"
git clean -f -d
git pull

if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi
git checkout "$branch"
git clean -f -d
git pull
if [ "$branch" != "master" ]; then
  cd build/jenkins
  for F in $(cat "$TEST_DIR/jenkins_scripts"); do
    git checkout master "$F"
  done
fi
